# ============================================================
# conditionsSD - configurazione S/4HC
# Communication Arrangement: SAP_COM_0294 + SAP_COM_0008
# ============================================================
#- P R O D U Z I O N E 
s4hc.baseUrl=https://my438840-api.s4hana.cloud.sap
#- Q U A L I T Y
#4hc.baseUrl=https://my434879-api.s4hana.cloud.sap

s4hc.username=JAVA_APP_USER
s4hc.password=JavaAppUser_23051995
s4hc.language=IT