# =============================================================================
# FCS WMS Bridge - Configurazione
# =============================================================================

# --- Connessione S/4HANA Cloud Public Edition ---
# -->  Sistema di test
#s4.base.url=https://my434879.s4hana.cloud.sap

# -->  Sistema di Produzione
s4.base.url=https://my438840.s4hana.cloud.sap

# Credenziali Communication User (Basic Auth)
s4.username=JAVA_APP_USER
s4.password=JavaAppUser_23051995

# Codice societ� (BUKRS)
s4.company.code=S001

# Lingua per le descrizioni (codice SAP: IT, EN, DE, ...)
s4.language=IT

# Plant principale (usato come filtro opzionale)
s4.plant=PL01

# Parametri Reso SD
kappl.reso = V
delivery.type.reso = LR

# IIdentificazione tipi di ordine di reso Lista separata da virgola
reso.sales.order.types = CBRE,RE,ZRE,ZRC

# Numero massimo record per pagina OData
s4.page.size=500

# Timeout connessione HTTP (secondi)
s4.http.timeout.connect=30

# Timeout lettura risposta HTTP (secondi)
s4.http.timeout.read=120

# --- Connessione PostgreSQL ---
# Formato: jdbc:postgresql://host:porta/database
db.url=jdbc:postgresql://localhost:5432/fcs
db.username=postgres
db.password=postgres

# Valore del campo "tenant" nelle tabelle FCS
db.tenant=undefined

# --- Logging ---
# Directory per i file di log (vuoto = solo console)
log.directory=C:/logs/fcs-wms-bridge
