# ============================================================
# Configurazione SAP S/4HANA Cloud - API Sales Order
# ============================================================
# ATTENZIONE: questo file NON deve essere committato su Git.
#             Aggiungere "config.properties" al .gitignore
# ============================================================

# URL base del sistema SAP (senza slash finale)
# -->  Sistema di test
sap.baseUrl=https://my434879.s4hana.cloud.sap

# -->  Sistema di Produzione
####sap.baseUrl=https://my438840.s4hana.cloud.sap


# Credenziali utente tecnico
sap.username=JAVA_APP_USER
sap.password=JavaAppUser_23051995

# Client SAP
sap.client=100

# ------------------------------------------------------------
#  URL app Fiori per visualizzazione ordini
# ------------------------------------------------------------
sap.url.va03  = /sap/bc/ui2/flp#SalesOrder-manage?SalesOrder=
sap.url.fiori = /sap/bc/ui2/flp#SalesOrder-displayFactSheet?SalesOrder=

# ------------------------------------------------------------
#  Excel \u2014 foglio
#
#  Nome del foglio da leggere nel file Excel.
#  Se il foglio non esiste, viene usato il primo foglio disponibile
#  e la statusbar mostra un avviso.
# ------------------------------------------------------------
excel.sheetName = Export

# ------------------------------------------------------------
#  Normalizzazione numero OdV ricevuto 
# Se questi parametri mancano, allora il numero ricevuto è quello dell'OdV in SAP
odv.virtual.prefix=113
odv.virtual.offset=1130000000
# ------------------------------------------------------------

# ------------------------------------------------------------
#  Excel \u2014 nomi colonne
#
#  Modificare solo se le intestazioni del file ricevuto
#  differiscono dai default qui indicati.
# ------------------------------------------------------------
excel.col.ordine        = Ordine
excel.col.posizione     = Pos.
excel.col.schedulazione = Sch.
excel.col.materiale     = Materiale
excel.col.materialeText = Descrizione
excel.col.quantita      = Qt\u00e0
excel.col.dataProd      = Data prod.
