CREATE TABLE IF NOT EXISTS TABFCSEKET
(
    tenant varchar(10),
    ebeln varchar(10),
    ebelp varchar(5),
    etenr varchar(4),
    PRIMARY KEY (tenant,ebeln,ebelp,etenr)
);
ALTER TABLE TABFCSEKET ADD COLUMN ameng numeric(13,3);
ALTER TABLE TABFCSEKET ALTER COLUMN ameng TYPE numeric(13,3);
ALTER TABLE TABFCSEKET ADD COLUMN bemid varchar(50);
ALTER TABLE TABFCSEKET ALTER COLUMN bemid TYPE varchar(50);
ALTER TABLE TABFCSEKET ADD COLUMN brgew_row numeric(13,3);
ALTER TABLE TABFCSEKET ALTER COLUMN brgew_row TYPE numeric(13,3);
ALTER TABLE TABFCSEKET ADD COLUMN bstme varchar(3);
ALTER TABLE TABFCSEKET ALTER COLUMN bstme TYPE varchar(3);
ALTER TABLE TABFCSEKET ADD COLUMN bstmexpallet int;
ALTER TABLE TABFCSEKET ALTER COLUMN bstmexpallet TYPE int;
ALTER TABLE TABFCSEKET ADD COLUMN charg varchar(10);
ALTER TABLE TABFCSEKET ALTER COLUMN charg TYPE varchar(10);
ALTER TABLE TABFCSEKET ADD COLUMN datum date;
ALTER TABLE TABFCSEKET ALTER COLUMN datum TYPE date;
ALTER TABLE TABFCSEKET ADD COLUMN eindt date;
ALTER TABLE TABFCSEKET ALTER COLUMN eindt TYPE date;
ALTER TABLE TABFCSEKET ADD COLUMN ernam varchar(12);
ALTER TABLE TABFCSEKET ALTER COLUMN ernam TYPE varchar(12);
ALTER TABLE TABFCSEKET ADD COLUMN gewei varchar(3);
ALTER TABLE TABFCSEKET ALTER COLUMN gewei TYPE varchar(3);
ALTER TABLE TABFCSEKET ADD COLUMN id_eket varchar(19);
ALTER TABLE TABFCSEKET ALTER COLUMN id_eket TYPE varchar(19);
ALTER TABLE TABFCSEKET ADD COLUMN in_bldat date;
ALTER TABLE TABFCSEKET ALTER COLUMN in_bldat TYPE date;
ALTER TABLE TABFCSEKET ADD COLUMN in_brgew_row numeric(13,3);
ALTER TABLE TABFCSEKET ALTER COLUMN in_brgew_row TYPE numeric(13,3);
ALTER TABLE TABFCSEKET ADD COLUMN in_brgew_tot numeric(13,3);
ALTER TABLE TABFCSEKET ALTER COLUMN in_brgew_tot TYPE numeric(13,3);
ALTER TABLE TABFCSEKET ADD COLUMN in_charg varchar(10);
ALTER TABLE TABFCSEKET ALTER COLUMN in_charg TYPE varchar(10);
ALTER TABLE TABFCSEKET ADD COLUMN in_colli_row int;
ALTER TABLE TABFCSEKET ALTER COLUMN in_colli_row TYPE int;
ALTER TABLE TABFCSEKET ADD COLUMN in_colli_tot int;
ALTER TABLE TABFCSEKET ALTER COLUMN in_colli_tot TYPE int;
ALTER TABLE TABFCSEKET ADD COLUMN in_data_arrivo date;
ALTER TABLE TABFCSEKET ALTER COLUMN in_data_arrivo TYPE date;
ALTER TABLE TABFCSEKET ADD COLUMN in_lgort varchar(4);
ALTER TABLE TABFCSEKET ALTER COLUMN in_lgort TYPE varchar(4);
ALTER TABLE TABFCSEKET ADD COLUMN in_menge numeric(13,3);
ALTER TABLE TABFCSEKET ALTER COLUMN in_menge TYPE numeric(13,3);
ALTER TABLE TABFCSEKET ADD COLUMN in_ntgew_row numeric(13,3);
ALTER TABLE TABFCSEKET ALTER COLUMN in_ntgew_row TYPE numeric(13,3);
ALTER TABLE TABFCSEKET ADD COLUMN in_ntgew_tot numeric(13,3);
ALTER TABLE TABFCSEKET ALTER COLUMN in_ntgew_tot TYPE numeric(13,3);
ALTER TABLE TABFCSEKET ADD COLUMN in_qtaxtag numeric(13,3);
ALTER TABLE TABFCSEKET ALTER COLUMN in_qtaxtag TYPE numeric(13,3);
ALTER TABLE TABFCSEKET ADD COLUMN in_traid varchar(20);
ALTER TABLE TABFCSEKET ALTER COLUMN in_traid TYPE varchar(20);
ALTER TABLE TABFCSEKET ADD COLUMN in_werks varchar(4);
ALTER TABLE TABFCSEKET ALTER COLUMN in_werks TYPE varchar(4);
ALTER TABLE TABFCSEKET ADD COLUMN in_xblnr varchar(16);
ALTER TABLE TABFCSEKET ALTER COLUMN in_xblnr TYPE varchar(16);
ALTER TABLE TABFCSEKET ADD COLUMN kappl varchar(2);
ALTER TABLE TABFCSEKET ALTER COLUMN kappl TYPE varchar(2);
ALTER TABLE TABFCSEKET ADD COLUMN lgort varchar(4);
ALTER TABLE TABFCSEKET ALTER COLUMN lgort TYPE varchar(4);
ALTER TABLE TABFCSEKET ADD COLUMN lifnr varchar(10);
ALTER TABLE TABFCSEKET ALTER COLUMN lifnr TYPE varchar(10);
ALTER TABLE TABFCSEKET ADD COLUMN maktx varchar(40);
ALTER TABLE TABFCSEKET ALTER COLUMN maktx TYPE varchar(40);
ALTER TABLE TABFCSEKET ADD COLUMN matnr varchar(18);
ALTER TABLE TABFCSEKET ALTER COLUMN matnr TYPE varchar(18);
ALTER TABLE TABFCSEKET ADD COLUMN meins varchar(3);
ALTER TABLE TABFCSEKET ALTER COLUMN meins TYPE varchar(3);
ALTER TABLE TABFCSEKET ADD COLUMN menge numeric(13,3);
ALTER TABLE TABFCSEKET ALTER COLUMN menge TYPE numeric(13,3);
ALTER TABLE TABFCSEKET ADD COLUMN menge_open numeric(13,3);
ALTER TABLE TABFCSEKET ALTER COLUMN menge_open TYPE numeric(13,3);
ALTER TABLE TABFCSEKET ADD COLUMN mengexbstme numeric(13,3);
ALTER TABLE TABFCSEKET ALTER COLUMN mengexbstme TYPE numeric(13,3);
ALTER TABLE TABFCSEKET ADD COLUMN mtart varchar(4);
ALTER TABLE TABFCSEKET ALTER COLUMN mtart TYPE varchar(4);
ALTER TABLE TABFCSEKET ADD COLUMN name1 varchar(80);
ALTER TABLE TABFCSEKET ALTER COLUMN name1 TYPE varchar(80);
ALTER TABLE TABFCSEKET ADD COLUMN nrbag int;
ALTER TABLE TABFCSEKET ALTER COLUMN nrbag TYPE int;
ALTER TABLE TABFCSEKET ADD COLUMN nrtag int;
ALTER TABLE TABFCSEKET ALTER COLUMN nrtag TYPE int;
ALTER TABLE TABFCSEKET ADD COLUMN ntgew_row numeric(13,3);
ALTER TABLE TABFCSEKET ALTER COLUMN ntgew_row TYPE numeric(13,3);
ALTER TABLE TABFCSEKET ADD COLUMN qtaxbag numeric(13,3);
ALTER TABLE TABFCSEKET ALTER COLUMN qtaxbag TYPE numeric(13,3);
ALTER TABLE TABFCSEKET ADD COLUMN qtaxtag numeric(13,3);
ALTER TABLE TABFCSEKET ALTER COLUMN qtaxtag TYPE numeric(13,3);
ALTER TABLE TABFCSEKET ADD COLUMN reswk varchar(4);
ALTER TABLE TABFCSEKET ALTER COLUMN reswk TYPE varchar(4);
ALTER TABLE TABFCSEKET ADD COLUMN tag_filler numeric(13,3);
ALTER TABLE TABFCSEKET ALTER COLUMN tag_filler TYPE numeric(13,3);
ALTER TABLE TABFCSEKET ADD COLUMN uzeit time;
ALTER TABLE TABFCSEKET ALTER COLUMN uzeit TYPE time;
ALTER TABLE TABFCSEKET ADD COLUMN wamng numeric(13,3);
ALTER TABLE TABFCSEKET ALTER COLUMN wamng TYPE numeric(13,3);
ALTER TABLE TABFCSEKET ADD COLUMN wemng numeric(13,3);
ALTER TABLE TABFCSEKET ALTER COLUMN wemng TYPE numeric(13,3);
ALTER TABLE TABFCSEKET ADD COLUMN werks varchar(4);
ALTER TABLE TABFCSEKET ALTER COLUMN werks TYPE varchar(4);
ALTER TABLE TABFCSEKET ADD COLUMN wmsst varchar(1);
ALTER TABLE TABFCSEKET ALTER COLUMN wmsst TYPE varchar(1);
ALTER TABLE TABFCSEKET ADD COLUMN xchpf boolean;
ALTER TABLE TABFCSEKET ALTER COLUMN xchpf TYPE boolean;
CREATE TABLE IF NOT EXISTS TABFCSMSEG
(
    tenant varchar(10),
    ebeln varchar(10),
    ebelp varchar(5),
    etenr varchar(4),
    in_charg varchar(10),
    in_xblnr varchar(16),
    PRIMARY KEY (tenant,ebeln,ebelp,etenr,in_charg,in_xblnr)
);
ALTER TABLE TABFCSMSEG ADD COLUMN bemid varchar(50);
ALTER TABLE TABFCSMSEG ALTER COLUMN bemid TYPE varchar(50);
ALTER TABLE TABFCSMSEG ADD COLUMN charg varchar(10);
ALTER TABLE TABFCSMSEG ALTER COLUMN charg TYPE varchar(10);
ALTER TABLE TABFCSMSEG ADD COLUMN datum date;
ALTER TABLE TABFCSMSEG ALTER COLUMN datum TYPE date;
ALTER TABLE TABFCSMSEG ADD COLUMN ernam varchar(12);
ALTER TABLE TABFCSMSEG ALTER COLUMN ernam TYPE varchar(12);
ALTER TABLE TABFCSMSEG ADD COLUMN id_eket varchar(19);
ALTER TABLE TABFCSMSEG ALTER COLUMN id_eket TYPE varchar(19);
ALTER TABLE TABFCSMSEG ADD COLUMN in_lgort varchar(4);
ALTER TABLE TABFCSMSEG ALTER COLUMN in_lgort TYPE varchar(4);
ALTER TABLE TABFCSMSEG ADD COLUMN in_menge numeric(13,3);
ALTER TABLE TABFCSMSEG ALTER COLUMN in_menge TYPE numeric(13,3);
ALTER TABLE TABFCSMSEG ADD COLUMN in_werks varchar(4);
ALTER TABLE TABFCSMSEG ALTER COLUMN in_werks TYPE varchar(4);
ALTER TABLE TABFCSMSEG ADD COLUMN kappl varchar(2);
ALTER TABLE TABFCSMSEG ALTER COLUMN kappl TYPE varchar(2);
ALTER TABLE TABFCSMSEG ADD COLUMN maktx varchar(40);
ALTER TABLE TABFCSMSEG ALTER COLUMN maktx TYPE varchar(40);
ALTER TABLE TABFCSMSEG ADD COLUMN meins varchar(3);
ALTER TABLE TABFCSMSEG ALTER COLUMN meins TYPE varchar(3);
ALTER TABLE TABFCSMSEG ADD COLUMN mtart varchar(4);
ALTER TABLE TABFCSMSEG ALTER COLUMN mtart TYPE varchar(4);
ALTER TABLE TABFCSMSEG ADD COLUMN uzeit time;
ALTER TABLE TABFCSMSEG ALTER COLUMN uzeit TYPE time;
ALTER TABLE TABFCSMSEG ADD COLUMN xchpf boolean;
ALTER TABLE TABFCSMSEG ALTER COLUMN xchpf TYPE boolean;
CREATE TABLE IF NOT EXISTS TABUMFOR
(
    tenant varchar(10),
    bstme varchar(3),
    datab date,
    lifnr varchar(10),
    matnr varchar(18),
    PRIMARY KEY (tenant,bstme,datab,lifnr,matnr)
);
ALTER TABLE TABUMFOR ADD COLUMN bstmexpallet int;
ALTER TABLE TABUMFOR ALTER COLUMN bstmexpallet TYPE int;
ALTER TABLE TABUMFOR ADD COLUMN meins varchar(3);
ALTER TABLE TABUMFOR ALTER COLUMN meins TYPE varchar(3);
ALTER TABLE TABUMFOR ADD COLUMN mengexbstme numeric(10,3);
ALTER TABLE TABUMFOR ALTER COLUMN mengexbstme TYPE numeric(10,3);
CREATE TABLE IF NOT EXISTS TABFCSEKETHST
(
    tenant varchar(10),
    ebeln varchar(10),
    ebelp varchar(5),
    etenr varchar(4),
    mblnr varchar(10),
    mjahr varchar(4),
    PRIMARY KEY (tenant,ebeln,ebelp,etenr,mblnr,mjahr)
);
ALTER TABLE TABFCSEKETHST ADD COLUMN ameng numeric(13,3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN ameng TYPE numeric(13,3);
ALTER TABLE TABFCSEKETHST ADD COLUMN bemid serial;
ALTER TABLE TABFCSEKETHST ALTER COLUMN bemid TYPE serial;
ALTER TABLE TABFCSEKETHST ADD COLUMN brgew_row numeric(13,3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN brgew_row TYPE numeric(13,3);
ALTER TABLE TABFCSEKETHST ADD COLUMN bstme varchar(3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN bstme TYPE varchar(3);
ALTER TABLE TABFCSEKETHST ADD COLUMN bstmexpallet int;
ALTER TABLE TABFCSEKETHST ALTER COLUMN bstmexpallet TYPE int;
ALTER TABLE TABFCSEKETHST ADD COLUMN charg varchar(10);
ALTER TABLE TABFCSEKETHST ALTER COLUMN charg TYPE varchar(10);
ALTER TABLE TABFCSEKETHST ADD COLUMN datum date;
ALTER TABLE TABFCSEKETHST ALTER COLUMN datum TYPE date;
ALTER TABLE TABFCSEKETHST ADD COLUMN eindt date;
ALTER TABLE TABFCSEKETHST ALTER COLUMN eindt TYPE date;
ALTER TABLE TABFCSEKETHST ADD COLUMN ernam varchar(12);
ALTER TABLE TABFCSEKETHST ALTER COLUMN ernam TYPE varchar(12);
ALTER TABLE TABFCSEKETHST ADD COLUMN gewei varchar(3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN gewei TYPE varchar(3);
ALTER TABLE TABFCSEKETHST ADD COLUMN id_eket varchar(19);
ALTER TABLE TABFCSEKETHST ALTER COLUMN id_eket TYPE varchar(19);
ALTER TABLE TABFCSEKETHST ADD COLUMN in_bldat date;
ALTER TABLE TABFCSEKETHST ALTER COLUMN in_bldat TYPE date;
ALTER TABLE TABFCSEKETHST ADD COLUMN in_brgew_tot numeric(13,3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN in_brgew_tot TYPE numeric(13,3);
ALTER TABLE TABFCSEKETHST ADD COLUMN in_colli_tot int;
ALTER TABLE TABFCSEKETHST ALTER COLUMN in_colli_tot TYPE int;
ALTER TABLE TABFCSEKETHST ADD COLUMN in_data_arrivo date;
ALTER TABLE TABFCSEKETHST ALTER COLUMN in_data_arrivo TYPE date;
ALTER TABLE TABFCSEKETHST ADD COLUMN in_ntgew_tot numeric(13,3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN in_ntgew_tot TYPE numeric(13,3);
ALTER TABLE TABFCSEKETHST ADD COLUMN in_qtaxtag numeric(13,3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN in_qtaxtag TYPE numeric(13,3);
ALTER TABLE TABFCSEKETHST ADD COLUMN in_traid varchar(20);
ALTER TABLE TABFCSEKETHST ALTER COLUMN in_traid TYPE varchar(20);
ALTER TABLE TABFCSEKETHST ADD COLUMN in_xblnr varchar(16);
ALTER TABLE TABFCSEKETHST ALTER COLUMN in_xblnr TYPE varchar(16);
ALTER TABLE TABFCSEKETHST ADD COLUMN kappl varchar(2);
ALTER TABLE TABFCSEKETHST ALTER COLUMN kappl TYPE varchar(2);
ALTER TABLE TABFCSEKETHST ADD COLUMN lgort varchar(4);
ALTER TABLE TABFCSEKETHST ALTER COLUMN lgort TYPE varchar(4);
ALTER TABLE TABFCSEKETHST ADD COLUMN lifnr varchar(10);
ALTER TABLE TABFCSEKETHST ALTER COLUMN lifnr TYPE varchar(10);
ALTER TABLE TABFCSEKETHST ADD COLUMN maktx varchar(40);
ALTER TABLE TABFCSEKETHST ALTER COLUMN maktx TYPE varchar(40);
ALTER TABLE TABFCSEKETHST ADD COLUMN meins varchar(3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN meins TYPE varchar(3);
ALTER TABLE TABFCSEKETHST ADD COLUMN menge numeric(13,3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN menge TYPE numeric(13,3);
ALTER TABLE TABFCSEKETHST ADD COLUMN menge_open numeric(13,3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN menge_open TYPE numeric(13,3);
ALTER TABLE TABFCSEKETHST ADD COLUMN mengexbstme numeric(10,3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN mengexbstme TYPE numeric(10,3);
ALTER TABLE TABFCSEKETHST ADD COLUMN mtart varchar(4);
ALTER TABLE TABFCSEKETHST ALTER COLUMN mtart TYPE varchar(4);
ALTER TABLE TABFCSEKETHST ADD COLUMN name1 varchar(80);
ALTER TABLE TABFCSEKETHST ALTER COLUMN name1 TYPE varchar(80);
ALTER TABLE TABFCSEKETHST ADD COLUMN nrbag int;
ALTER TABLE TABFCSEKETHST ALTER COLUMN nrbag TYPE int;
ALTER TABLE TABFCSEKETHST ADD COLUMN nrtag int;
ALTER TABLE TABFCSEKETHST ALTER COLUMN nrtag TYPE int;
ALTER TABLE TABFCSEKETHST ADD COLUMN ntgew_row numeric(13,3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN ntgew_row TYPE numeric(13,3);
ALTER TABLE TABFCSEKETHST ADD COLUMN qtaxbag numeric(13,3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN qtaxbag TYPE numeric(13,3);
ALTER TABLE TABFCSEKETHST ADD COLUMN qtaxtag numeric(13,3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN qtaxtag TYPE numeric(13,3);
ALTER TABLE TABFCSEKETHST ADD COLUMN reswk varchar(4);
ALTER TABLE TABFCSEKETHST ALTER COLUMN reswk TYPE varchar(4);
ALTER TABLE TABFCSEKETHST ADD COLUMN tag_filler numeric(13,3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN tag_filler TYPE numeric(13,3);
ALTER TABLE TABFCSEKETHST ADD COLUMN uzeit time;
ALTER TABLE TABFCSEKETHST ALTER COLUMN uzeit TYPE time;
ALTER TABLE TABFCSEKETHST ADD COLUMN wamng numeric(13,3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN wamng TYPE numeric(13,3);
ALTER TABLE TABFCSEKETHST ADD COLUMN wemng numeric(13,3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN wemng TYPE numeric(13,3);
ALTER TABLE TABFCSEKETHST ADD COLUMN werks varchar(4);
ALTER TABLE TABFCSEKETHST ALTER COLUMN werks TYPE varchar(4);
ALTER TABLE TABFCSEKETHST ADD COLUMN wmsst varchar(1);
ALTER TABLE TABFCSEKETHST ALTER COLUMN wmsst TYPE varchar(1);
ALTER TABLE TABFCSEKETHST ADD COLUMN xchpf boolean;
ALTER TABLE TABFCSEKETHST ALTER COLUMN xchpf TYPE boolean;
CREATE TABLE IF NOT EXISTS TABFCST001
(
    tenant varchar(10),
    mtart varchar(4),
    werks varchar(4),
    PRIMARY KEY (tenant,mtart,werks)
);
ALTER TABLE TABFCST001 ADD COLUMN exp2fcs boolean;
ALTER TABLE TABFCST001 ALTER COLUMN exp2fcs TYPE boolean;
CREATE TABLE IF NOT EXISTS TABFCSKNA1
(
    tenant varchar(10),
    kunnr varchar(10),
    PRIMARY KEY (tenant,kunnr)
);
ALTER TABLE TABFCSKNA1 ADD COLUMN datum date;
ALTER TABLE TABFCSKNA1 ALTER COLUMN datum TYPE date;
ALTER TABLE TABFCSKNA1 ADD COLUMN name1 varchar(80);
ALTER TABLE TABFCSKNA1 ALTER COLUMN name1 TYPE varchar(80);
ALTER TABLE TABFCSKNA1 ADD COLUMN name2 varchar(80);
ALTER TABLE TABFCSKNA1 ALTER COLUMN name2 TYPE varchar(80);
ALTER TABLE TABFCSKNA1 ADD COLUMN stcd1 varchar(16);
ALTER TABLE TABFCSKNA1 ALTER COLUMN stcd1 TYPE varchar(16);
ALTER TABLE TABFCSKNA1 ADD COLUMN stcd2 varchar(11);
ALTER TABLE TABFCSKNA1 ALTER COLUMN stcd2 TYPE varchar(11);
ALTER TABLE TABFCSKNA1 ADD COLUMN stceg varchar(20);
ALTER TABLE TABFCSKNA1 ALTER COLUMN stceg TYPE varchar(20);
ALTER TABLE TABFCSKNA1 ADD COLUMN uname varchar(12);
ALTER TABLE TABFCSKNA1 ALTER COLUMN uname TYPE varchar(12);
ALTER TABLE TABFCSKNA1 ADD COLUMN updfl boolean;
ALTER TABLE TABFCSKNA1 ALTER COLUMN updfl TYPE boolean;
ALTER TABLE TABFCSKNA1 ADD COLUMN uzeit time;
ALTER TABLE TABFCSKNA1 ALTER COLUMN uzeit TYPE time;
CREATE TABLE IF NOT EXISTS TABFCSMSEGHST
(
    tenant varchar(10),
    ebeln varchar(10),
    ebelp varchar(5),
    etenr varchar(4),
    in_charg varchar(10),
    in_xblnr varchar(16),
    mblnr varchar(10),
    mjahr varchar(4),
    PRIMARY KEY (tenant,ebeln,ebelp,etenr,in_charg,in_xblnr,mblnr,mjahr)
);
ALTER TABLE TABFCSMSEGHST ADD COLUMN bemid varchar(50);
ALTER TABLE TABFCSMSEGHST ALTER COLUMN bemid TYPE varchar(50);
ALTER TABLE TABFCSMSEGHST ADD COLUMN charg varchar(10);
ALTER TABLE TABFCSMSEGHST ALTER COLUMN charg TYPE varchar(10);
ALTER TABLE TABFCSMSEGHST ADD COLUMN datum date;
ALTER TABLE TABFCSMSEGHST ALTER COLUMN datum TYPE date;
ALTER TABLE TABFCSMSEGHST ADD COLUMN ernam varchar(12);
ALTER TABLE TABFCSMSEGHST ALTER COLUMN ernam TYPE varchar(12);
ALTER TABLE TABFCSMSEGHST ADD COLUMN id_eket varchar(19);
ALTER TABLE TABFCSMSEGHST ALTER COLUMN id_eket TYPE varchar(19);
ALTER TABLE TABFCSMSEGHST ADD COLUMN in_lgort varchar(4);
ALTER TABLE TABFCSMSEGHST ALTER COLUMN in_lgort TYPE varchar(4);
ALTER TABLE TABFCSMSEGHST ADD COLUMN in_menge numeric(13,3);
ALTER TABLE TABFCSMSEGHST ALTER COLUMN in_menge TYPE numeric(13,3);
ALTER TABLE TABFCSMSEGHST ADD COLUMN in_werks varchar(4);
ALTER TABLE TABFCSMSEGHST ALTER COLUMN in_werks TYPE varchar(4);
ALTER TABLE TABFCSMSEGHST ADD COLUMN kappl varchar(2);
ALTER TABLE TABFCSMSEGHST ALTER COLUMN kappl TYPE varchar(2);
ALTER TABLE TABFCSMSEGHST ADD COLUMN maktx varchar(40);
ALTER TABLE TABFCSMSEGHST ALTER COLUMN maktx TYPE varchar(40);
ALTER TABLE TABFCSMSEGHST ADD COLUMN matnr varchar(18);
ALTER TABLE TABFCSMSEGHST ALTER COLUMN matnr TYPE varchar(18);
ALTER TABLE TABFCSMSEGHST ADD COLUMN meins varchar(3);
ALTER TABLE TABFCSMSEGHST ALTER COLUMN meins TYPE varchar(3);
ALTER TABLE TABFCSMSEGHST ADD COLUMN mtart varchar(4);
ALTER TABLE TABFCSMSEGHST ALTER COLUMN mtart TYPE varchar(4);
ALTER TABLE TABFCSMSEGHST ADD COLUMN uzeit time;
ALTER TABLE TABFCSMSEGHST ALTER COLUMN uzeit TYPE time;
CREATE TABLE IF NOT EXISTS TABFCSMOVSAP
(
    tenant varchar(10),
    movid varchar(50),
    PRIMARY KEY (tenant,movid)
);
ALTER TABLE TABFCSMOVSAP ADD COLUMN aufnr varchar(12);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN aufnr TYPE varchar(12);
ALTER TABLE TABFCSMOVSAP ADD COLUMN bwart varchar(3);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN bwart TYPE varchar(3);
ALTER TABLE TABFCSMOVSAP ADD COLUMN charg varchar(10);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN charg TYPE varchar(10);
ALTER TABLE TABFCSMOVSAP ADD COLUMN charg_to varchar(10);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN charg_to TYPE varchar(10);
ALTER TABLE TABFCSMOVSAP ADD COLUMN datum date;
ALTER TABLE TABFCSMOVSAP ALTER COLUMN datum TYPE date;
ALTER TABLE TABFCSMOVSAP ADD COLUMN kostl varchar(10);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN kostl TYPE varchar(10);
ALTER TABLE TABFCSMOVSAP ADD COLUMN kunnr varchar(10);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN kunnr TYPE varchar(10);
ALTER TABLE TABFCSMOVSAP ADD COLUMN lgort varchar(4);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN lgort TYPE varchar(4);
ALTER TABLE TABFCSMOVSAP ADD COLUMN lgort_to varchar(4);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN lgort_to TYPE varchar(4);
ALTER TABLE TABFCSMOVSAP ADD COLUMN lifnr varchar(10);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN lifnr TYPE varchar(10);
ALTER TABLE TABFCSMOVSAP ADD COLUMN matnr varchar(18);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN matnr TYPE varchar(18);
ALTER TABLE TABFCSMOVSAP ADD COLUMN matnr_to varchar(18);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN matnr_to TYPE varchar(18);
ALTER TABLE TABFCSMOVSAP ADD COLUMN meins varchar(3);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN meins TYPE varchar(3);
ALTER TABLE TABFCSMOVSAP ADD COLUMN menge numeric(13,3);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN menge TYPE numeric(13,3);
ALTER TABLE TABFCSMOVSAP ADD COLUMN menge_to numeric(13,3);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN menge_to TYPE numeric(13,3);
ALTER TABLE TABFCSMOVSAP ADD COLUMN prctr varchar(10);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN prctr TYPE varchar(10);
ALTER TABLE TABFCSMOVSAP ADD COLUMN sobkz varchar(1);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN sobkz TYPE varchar(1);
ALTER TABLE TABFCSMOVSAP ADD COLUMN uname varchar(12);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN uname TYPE varchar(12);
ALTER TABLE TABFCSMOVSAP ADD COLUMN uzeit time;
ALTER TABLE TABFCSMOVSAP ALTER COLUMN uzeit TYPE time;
ALTER TABLE TABFCSMOVSAP ADD COLUMN werks varchar(4);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN werks TYPE varchar(4);
ALTER TABLE TABFCSMOVSAP ADD COLUMN werks_to varchar(4);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN werks_to TYPE varchar(4);
ALTER TABLE TABFCSMOVSAP ADD COLUMN wmsst varchar(1);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN wmsst TYPE varchar(1);
CREATE TABLE IF NOT EXISTS TABFCSMOVSAPHST
(
    tenant varchar(10),
    movid varchar(50),
    PRIMARY KEY (tenant,movid)
);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN aufnr varchar(12);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN aufnr TYPE varchar(12);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN mblnr varchar(10);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN mblnr TYPE varchar(10);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN mjahr varchar(4);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN mjahr TYPE varchar(4);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN bwart varchar(3);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN bwart TYPE varchar(3);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN charg varchar(10);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN charg TYPE varchar(10);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN charg_to varchar(10);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN charg_to TYPE varchar(10);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN datum date;
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN datum TYPE date;
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN kostl varchar(10);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN kostl TYPE varchar(10);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN kunnr varchar(10);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN kunnr TYPE varchar(10);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN lgort varchar(4);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN lgort TYPE varchar(4);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN lgort_to varchar(4);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN lgort_to TYPE varchar(4);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN lifnr varchar(10);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN lifnr TYPE varchar(10);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN matnr varchar(18);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN matnr TYPE varchar(18);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN matnr_to varchar(18);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN matnr_to TYPE varchar(18);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN meins varchar(3);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN meins TYPE varchar(3);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN menge numeric(13,3);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN menge TYPE numeric(13,3);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN menge_to numeric(13,3);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN menge_to TYPE numeric(13,3);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN prctr varchar(10);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN prctr TYPE varchar(10);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN sobkz varchar(1);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN sobkz TYPE varchar(1);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN uname varchar(12);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN uname TYPE varchar(12);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN uzeit time;
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN uzeit TYPE time;
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN werks varchar(4);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN werks TYPE varchar(4);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN werks_to varchar(4);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN werks_to TYPE varchar(4);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN wmsst varchar(1);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN wmsst TYPE varchar(1);
CREATE TABLE IF NOT EXISTS TABFCSMARA
(
    tenant varchar(10),
    matnr varchar(18),
    PRIMARY KEY (tenant,matnr)
);
ALTER TABLE TABFCSMARA ADD COLUMN bstme varchar(3);
ALTER TABLE TABFCSMARA ALTER COLUMN bstme TYPE varchar(3);
ALTER TABLE TABFCSMARA ADD COLUMN datum date;
ALTER TABLE TABFCSMARA ALTER COLUMN datum TYPE date;
ALTER TABLE TABFCSMARA ADD COLUMN maktx varchar(40);
ALTER TABLE TABFCSMARA ALTER COLUMN maktx TYPE varchar(40);
ALTER TABLE TABFCSMARA ADD COLUMN matkl varchar(9);
ALTER TABLE TABFCSMARA ALTER COLUMN matkl TYPE varchar(9);
ALTER TABLE TABFCSMARA ADD COLUMN meins varchar(3);
ALTER TABLE TABFCSMARA ALTER COLUMN meins TYPE varchar(3);
ALTER TABLE TABFCSMARA ADD COLUMN mtart varchar(4);
ALTER TABLE TABFCSMARA ALTER COLUMN mtart TYPE varchar(4);
ALTER TABLE TABFCSMARA ADD COLUMN uname varchar(12);
ALTER TABLE TABFCSMARA ALTER COLUMN uname TYPE varchar(12);
ALTER TABLE TABFCSMARA ADD COLUMN updfl boolean;
ALTER TABLE TABFCSMARA ALTER COLUMN updfl TYPE boolean;
ALTER TABLE TABFCSMARA ADD COLUMN uzeit time;
ALTER TABLE TABFCSMARA ALTER COLUMN uzeit TYPE time;
CREATE TABLE IF NOT EXISTS TABUMCLI
(
    tenant varchar(10),
    bstme varchar(3),
    datab date,
    kunnr varchar(10),
    matnr varchar(18),
    PRIMARY KEY (tenant,bstme,datab,kunnr,matnr)
);
ALTER TABLE TABUMCLI ADD COLUMN bstmexpallet int;
ALTER TABLE TABUMCLI ALTER COLUMN bstmexpallet TYPE int;
ALTER TABLE TABUMCLI ADD COLUMN meins varchar(3);
ALTER TABLE TABUMCLI ALTER COLUMN meins TYPE varchar(3);
ALTER TABLE TABUMCLI ADD COLUMN mengexbstme numeric(10,3);
ALTER TABLE TABUMCLI ALTER COLUMN mengexbstme TYPE numeric(10,3);
CREATE TABLE IF NOT EXISTS TABFCSLFA1
(
    tenant varchar(10),
    lifnr varchar(10),
    PRIMARY KEY (tenant,lifnr)
);
ALTER TABLE TABFCSLFA1 ADD COLUMN datum date;
ALTER TABLE TABFCSLFA1 ALTER COLUMN datum TYPE date;
ALTER TABLE TABFCSLFA1 ADD COLUMN name1 varchar(80);
ALTER TABLE TABFCSLFA1 ALTER COLUMN name1 TYPE varchar(80);
ALTER TABLE TABFCSLFA1 ADD COLUMN name2 varchar(80);
ALTER TABLE TABFCSLFA1 ALTER COLUMN name2 TYPE varchar(80);
ALTER TABLE TABFCSLFA1 ADD COLUMN stcd1 varchar(16);
ALTER TABLE TABFCSLFA1 ALTER COLUMN stcd1 TYPE varchar(16);
ALTER TABLE TABFCSLFA1 ADD COLUMN stcd2 varchar(11);
ALTER TABLE TABFCSLFA1 ALTER COLUMN stcd2 TYPE varchar(11);
ALTER TABLE TABFCSLFA1 ADD COLUMN stceg varchar(20);
ALTER TABLE TABFCSLFA1 ALTER COLUMN stceg TYPE varchar(20);
ALTER TABLE TABFCSLFA1 ADD COLUMN uname varchar(12);
ALTER TABLE TABFCSLFA1 ALTER COLUMN uname TYPE varchar(12);
ALTER TABLE TABFCSLFA1 ADD COLUMN updfl boolean;
ALTER TABLE TABFCSLFA1 ALTER COLUMN updfl TYPE boolean;
ALTER TABLE TABFCSLFA1 ADD COLUMN uzeit time;
ALTER TABLE TABFCSLFA1 ALTER COLUMN uzeit TYPE time;
