CREATE TABLE IF NOT EXISTS TABFCSMSEGHST
(
    tenant varchar(10),
    ebeln varchar(10),
    ebelp varchar(5),
    etenr varchar(4),
    in_charg varchar(10),
    in_xblnr varchar(16),
    mblnr varchar(10),
    mjahr varchar(4),
    PRIMARY KEY (tenant,ebeln,ebelp,etenr,in_charg,in_xblnr,mblnr,mjahr)
);
ALTER TABLE TABFCSMSEGHST ADD COLUMN bemid varchar(36);
ALTER TABLE TABFCSMSEGHST ALTER COLUMN bemid TYPE varchar(36);
ALTER TABLE TABFCSMSEGHST ADD COLUMN charg varchar(10);
ALTER TABLE TABFCSMSEGHST ALTER COLUMN charg TYPE varchar(10);
ALTER TABLE TABFCSMSEGHST ADD COLUMN datum date;
ALTER TABLE TABFCSMSEGHST ALTER COLUMN datum TYPE date;
ALTER TABLE TABFCSMSEGHST ADD COLUMN ernam varchar(12);
ALTER TABLE TABFCSMSEGHST ALTER COLUMN ernam TYPE varchar(12);
ALTER TABLE TABFCSMSEGHST ADD COLUMN id_eket varchar(19);
ALTER TABLE TABFCSMSEGHST ALTER COLUMN id_eket TYPE varchar(19);
ALTER TABLE TABFCSMSEGHST ADD COLUMN in_lgort varchar(4);
ALTER TABLE TABFCSMSEGHST ALTER COLUMN in_lgort TYPE varchar(4);
ALTER TABLE TABFCSMSEGHST ADD COLUMN in_mange numeric(13,3);
ALTER TABLE TABFCSMSEGHST ALTER COLUMN in_mange TYPE numeric(13,3);
ALTER TABLE TABFCSMSEGHST ADD COLUMN in_werks varchar(4);
ALTER TABLE TABFCSMSEGHST ALTER COLUMN in_werks TYPE varchar(4);
ALTER TABLE TABFCSMSEGHST ADD COLUMN kappl varchar(2);
ALTER TABLE TABFCSMSEGHST ALTER COLUMN kappl TYPE varchar(2);
ALTER TABLE TABFCSMSEGHST ADD COLUMN maktx varchar(40);
ALTER TABLE TABFCSMSEGHST ALTER COLUMN maktx TYPE varchar(40);
ALTER TABLE TABFCSMSEGHST ADD COLUMN matnr varchar(18);
ALTER TABLE TABFCSMSEGHST ALTER COLUMN matnr TYPE varchar(18);
ALTER TABLE TABFCSMSEGHST ADD COLUMN meins varchar(3);
ALTER TABLE TABFCSMSEGHST ALTER COLUMN meins TYPE varchar(3);
ALTER TABLE TABFCSMSEGHST ADD COLUMN mtart varchar(4);
ALTER TABLE TABFCSMSEGHST ALTER COLUMN mtart TYPE varchar(4);
ALTER TABLE TABFCSMSEGHST ADD COLUMN uzeit time;
ALTER TABLE TABFCSMSEGHST ALTER COLUMN uzeit TYPE time;
