CREATE TABLE IF NOT EXISTS TABFCSSYNC
(
    tenant varchar(10),
    entity varchar(30),
    PRIMARY KEY (tenant,entity)
);
ALTER TABLE TABFCSSYNC ADD COLUMN last_count int;
ALTER TABLE TABFCSSYNC ALTER COLUMN last_count TYPE int;
ALTER TABLE TABFCSSYNC ADD COLUMN last_error varchar(500);
ALTER TABLE TABFCSSYNC ALTER COLUMN last_error TYPE varchar(500);
ALTER TABLE TABFCSSYNC ADD COLUMN last_status varchar(10);
ALTER TABLE TABFCSSYNC ALTER COLUMN last_status TYPE varchar(10);
ALTER TABLE TABFCSSYNC ADD COLUMN last_sync timestamp;
ALTER TABLE TABFCSSYNC ALTER COLUMN last_sync TYPE timestamp;
ALTER TABLE TABFCSSYNC ADD COLUMN last_upserted int;
ALTER TABLE TABFCSSYNC ALTER COLUMN last_upserted TYPE int;
ALTER TABLE TABFCSSYNC ADD COLUMN next_sync_from timestamp;
ALTER TABLE TABFCSSYNC ALTER COLUMN next_sync_from TYPE timestamp;
ALTER TABLE TABFCSSYNC ADD COLUMN created_at timestamp;
ALTER TABLE TABFCSSYNC ALTER COLUMN created_at TYPE timestamp;
ALTER TABLE TABFCSSYNC ADD COLUMN updated_at timestamp;
ALTER TABLE TABFCSSYNC ALTER COLUMN updated_at TYPE timestamp;
ALTER TABLE TABFCSSYNC ADD COLUMN last_duration_ms bigint;
ALTER TABLE TABFCSSYNC ALTER COLUMN last_duration_ms TYPE bigint;
