CREATE TABLE IF NOT EXISTS TABFCSEKETHST
(
    tenant varchar(10),
    ebeln varchar(10),
    ebelp varchar(6),
    etenr varchar(4),
    mblnr varchar(10),
    mjahr varchar(4),
    PRIMARY KEY (tenant,ebeln,ebelp,etenr,mblnr,mjahr)
);
ALTER TABLE TABFCSEKETHST ADD COLUMN ameng numeric(13,3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN ameng TYPE numeric(13,3);
ALTER TABLE TABFCSEKETHST ADD COLUMN bemid serial;
ALTER TABLE TABFCSEKETHST ALTER COLUMN bemid TYPE serial;
ALTER TABLE TABFCSEKETHST ADD COLUMN brgew_row numeric(13,3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN brgew_row TYPE numeric(13,3);
ALTER TABLE TABFCSEKETHST ADD COLUMN bstme varchar(3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN bstme TYPE varchar(3);
ALTER TABLE TABFCSEKETHST ADD COLUMN bstmexpallet int;
ALTER TABLE TABFCSEKETHST ALTER COLUMN bstmexpallet TYPE int;
ALTER TABLE TABFCSEKETHST ADD COLUMN charg varchar(10);
ALTER TABLE TABFCSEKETHST ALTER COLUMN charg TYPE varchar(10);
ALTER TABLE TABFCSEKETHST ADD COLUMN datum date;
ALTER TABLE TABFCSEKETHST ALTER COLUMN datum TYPE date;
ALTER TABLE TABFCSEKETHST ADD COLUMN eindt date;
ALTER TABLE TABFCSEKETHST ALTER COLUMN eindt TYPE date;
ALTER TABLE TABFCSEKETHST ADD COLUMN ernam varchar(12);
ALTER TABLE TABFCSEKETHST ALTER COLUMN ernam TYPE varchar(12);
ALTER TABLE TABFCSEKETHST ADD COLUMN gewei varchar(3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN gewei TYPE varchar(3);
ALTER TABLE TABFCSEKETHST ADD COLUMN id_eket varchar(24);
ALTER TABLE TABFCSEKETHST ALTER COLUMN id_eket TYPE varchar(24);
ALTER TABLE TABFCSEKETHST ADD COLUMN in_bldat date;
ALTER TABLE TABFCSEKETHST ALTER COLUMN in_bldat TYPE date;
ALTER TABLE TABFCSEKETHST ADD COLUMN in_brgew_tot numeric(13,3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN in_brgew_tot TYPE numeric(13,3);
ALTER TABLE TABFCSEKETHST ADD COLUMN in_colli_tot int;
ALTER TABLE TABFCSEKETHST ALTER COLUMN in_colli_tot TYPE int;
ALTER TABLE TABFCSEKETHST ADD COLUMN in_data_arrivo date;
ALTER TABLE TABFCSEKETHST ALTER COLUMN in_data_arrivo TYPE date;
ALTER TABLE TABFCSEKETHST ADD COLUMN in_ntgew_tot numeric(13,3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN in_ntgew_tot TYPE numeric(13,3);
ALTER TABLE TABFCSEKETHST ADD COLUMN in_qtaxtag numeric(13,3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN in_qtaxtag TYPE numeric(13,3);
ALTER TABLE TABFCSEKETHST ADD COLUMN in_traid varchar(20);
ALTER TABLE TABFCSEKETHST ALTER COLUMN in_traid TYPE varchar(20);
ALTER TABLE TABFCSEKETHST ADD COLUMN in_xblnr varchar(16);
ALTER TABLE TABFCSEKETHST ALTER COLUMN in_xblnr TYPE varchar(16);
ALTER TABLE TABFCSEKETHST ADD COLUMN kappl varchar(2);
ALTER TABLE TABFCSEKETHST ALTER COLUMN kappl TYPE varchar(2);
ALTER TABLE TABFCSEKETHST ADD COLUMN lgort varchar(4);
ALTER TABLE TABFCSEKETHST ALTER COLUMN lgort TYPE varchar(4);
ALTER TABLE TABFCSEKETHST ADD COLUMN lifnr varchar(10);
ALTER TABLE TABFCSEKETHST ALTER COLUMN lifnr TYPE varchar(10);
ALTER TABLE TABFCSEKETHST ADD COLUMN maktx varchar(40);
ALTER TABLE TABFCSEKETHST ALTER COLUMN maktx TYPE varchar(40);
ALTER TABLE TABFCSEKETHST ADD COLUMN meins varchar(3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN meins TYPE varchar(3);
ALTER TABLE TABFCSEKETHST ADD COLUMN menge numeric(13,3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN menge TYPE numeric(13,3);
ALTER TABLE TABFCSEKETHST ADD COLUMN menge_open numeric(13,3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN menge_open TYPE numeric(13,3);
ALTER TABLE TABFCSEKETHST ADD COLUMN mengexbstme numeric(10,3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN mengexbstme TYPE numeric(10,3);
ALTER TABLE TABFCSEKETHST ADD COLUMN mtart varchar(4);
ALTER TABLE TABFCSEKETHST ALTER COLUMN mtart TYPE varchar(4);
ALTER TABLE TABFCSEKETHST ADD COLUMN name1 varchar(80);
ALTER TABLE TABFCSEKETHST ALTER COLUMN name1 TYPE varchar(80);
ALTER TABLE TABFCSEKETHST ADD COLUMN nrbag int;
ALTER TABLE TABFCSEKETHST ALTER COLUMN nrbag TYPE int;
ALTER TABLE TABFCSEKETHST ADD COLUMN nrtag int;
ALTER TABLE TABFCSEKETHST ALTER COLUMN nrtag TYPE int;
ALTER TABLE TABFCSEKETHST ADD COLUMN ntgew_row numeric(13,3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN ntgew_row TYPE numeric(13,3);
ALTER TABLE TABFCSEKETHST ADD COLUMN qtaxbag numeric(13,3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN qtaxbag TYPE numeric(13,3);
ALTER TABLE TABFCSEKETHST ADD COLUMN qtaxtag numeric(13,3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN qtaxtag TYPE numeric(13,3);
ALTER TABLE TABFCSEKETHST ADD COLUMN reswk varchar(4);
ALTER TABLE TABFCSEKETHST ALTER COLUMN reswk TYPE varchar(4);
ALTER TABLE TABFCSEKETHST ADD COLUMN tag_filler numeric(13,3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN tag_filler TYPE numeric(13,3);
ALTER TABLE TABFCSEKETHST ADD COLUMN uzeit time;
ALTER TABLE TABFCSEKETHST ALTER COLUMN uzeit TYPE time;
ALTER TABLE TABFCSEKETHST ADD COLUMN wamng numeric(13,3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN wamng TYPE numeric(13,3);
ALTER TABLE TABFCSEKETHST ADD COLUMN wemng numeric(13,3);
ALTER TABLE TABFCSEKETHST ALTER COLUMN wemng TYPE numeric(13,3);
ALTER TABLE TABFCSEKETHST ADD COLUMN werks varchar(4);
ALTER TABLE TABFCSEKETHST ALTER COLUMN werks TYPE varchar(4);
ALTER TABLE TABFCSEKETHST ADD COLUMN wmsst varchar(1);
ALTER TABLE TABFCSEKETHST ALTER COLUMN wmsst TYPE varchar(1);
ALTER TABLE TABFCSEKETHST ADD COLUMN xchpf boolean;
ALTER TABLE TABFCSEKETHST ALTER COLUMN xchpf TYPE boolean;
