CREATE TABLE IF NOT EXISTS TABFCSRESTLOG
(
    tenant varchar(10),
    prog int,
    zdatetime timestamp,
    PRIMARY KEY (tenant,prog,zdatetime)
);
ALTER TABLE TABFCSRESTLOG ADD COLUMN http_method varchar(50);
ALTER TABLE TABFCSRESTLOG ALTER COLUMN http_method TYPE varchar(50);
ALTER TABLE TABFCSRESTLOG ADD COLUMN id_eket varchar(24);
ALTER TABLE TABFCSRESTLOG ALTER COLUMN id_eket TYPE varchar(24);
ALTER TABLE TABFCSRESTLOG ADD COLUMN movid varchar(50);
ALTER TABLE TABFCSRESTLOG ALTER COLUMN movid TYPE varchar(50);
ALTER TABLE TABFCSRESTLOG ADD COLUMN query_string varchar(500);
ALTER TABLE TABFCSRESTLOG ALTER COLUMN query_string TYPE varchar(500);
ALTER TABLE TABFCSRESTLOG ADD COLUMN response varchar(500);
ALTER TABLE TABFCSRESTLOG ALTER COLUMN response TYPE varchar(500);
