CREATE TABLE IF NOT EXISTS TABFCSMARA
(
    tenant varchar(10),
    matnr varchar(18),
    PRIMARY KEY (tenant,matnr)
);
ALTER TABLE TABFCSMARA ADD COLUMN brgew numeric(13,3);
ALTER TABLE TABFCSMARA ALTER COLUMN brgew TYPE numeric(13,3);
ALTER TABLE TABFCSMARA ADD COLUMN bstme varchar(3);
ALTER TABLE TABFCSMARA ALTER COLUMN bstme TYPE varchar(3);
ALTER TABLE TABFCSMARA ADD COLUMN datum date;
ALTER TABLE TABFCSMARA ALTER COLUMN datum TYPE date;
ALTER TABLE TABFCSMARA ADD COLUMN gewei varchar(3);
ALTER TABLE TABFCSMARA ALTER COLUMN gewei TYPE varchar(3);
ALTER TABLE TABFCSMARA ADD COLUMN maktx varchar(40);
ALTER TABLE TABFCSMARA ALTER COLUMN maktx TYPE varchar(40);
ALTER TABLE TABFCSMARA ADD COLUMN matkl varchar(9);
ALTER TABLE TABFCSMARA ALTER COLUMN matkl TYPE varchar(9);
ALTER TABLE TABFCSMARA ADD COLUMN meins varchar(3);
ALTER TABLE TABFCSMARA ALTER COLUMN meins TYPE varchar(3);
ALTER TABLE TABFCSMARA ADD COLUMN mtart varchar(4);
ALTER TABLE TABFCSMARA ALTER COLUMN mtart TYPE varchar(4);
ALTER TABLE TABFCSMARA ADD COLUMN ntgew numeric(13,3);
ALTER TABLE TABFCSMARA ALTER COLUMN ntgew TYPE numeric(13,3);
ALTER TABLE TABFCSMARA ADD COLUMN uname varchar(12);
ALTER TABLE TABFCSMARA ALTER COLUMN uname TYPE varchar(12);
ALTER TABLE TABFCSMARA ADD COLUMN updfl boolean;
ALTER TABLE TABFCSMARA ALTER COLUMN updfl TYPE boolean;
ALTER TABLE TABFCSMARA ADD COLUMN uzeit time;
ALTER TABLE TABFCSMARA ALTER COLUMN uzeit TYPE time;
