CREATE TABLE IF NOT EXISTS TABFCSMSEG
(
    tenant varchar(10),
    ebeln varchar(10),
    ebelp varchar(5),
    etenr varchar(4),
    in_charg varchar(10),
    in_xblnr varchar(16),
    PRIMARY KEY (tenant,ebeln,ebelp,etenr,in_charg,in_xblnr)
);
ALTER TABLE TABFCSMSEG ADD COLUMN bemid varchar(36);
ALTER TABLE TABFCSMSEG ALTER COLUMN bemid TYPE varchar(36);
ALTER TABLE TABFCSMSEG ADD COLUMN charg varchar(10);
ALTER TABLE TABFCSMSEG ALTER COLUMN charg TYPE varchar(10);
ALTER TABLE TABFCSMSEG ADD COLUMN datum date;
ALTER TABLE TABFCSMSEG ALTER COLUMN datum TYPE date;
ALTER TABLE TABFCSMSEG ADD COLUMN ernam varchar(12);
ALTER TABLE TABFCSMSEG ALTER COLUMN ernam TYPE varchar(12);
ALTER TABLE TABFCSMSEG ADD COLUMN id_eket varchar(19);
ALTER TABLE TABFCSMSEG ALTER COLUMN id_eket TYPE varchar(19);
ALTER TABLE TABFCSMSEG ADD COLUMN in_lgort varchar(4);
ALTER TABLE TABFCSMSEG ALTER COLUMN in_lgort TYPE varchar(4);
ALTER TABLE TABFCSMSEG ADD COLUMN in_menge numeric(13,3);
ALTER TABLE TABFCSMSEG ALTER COLUMN in_menge TYPE numeric(13,3);
ALTER TABLE TABFCSMSEG ADD COLUMN in_werks varchar(4);
ALTER TABLE TABFCSMSEG ALTER COLUMN in_werks TYPE varchar(4);
ALTER TABLE TABFCSMSEG ADD COLUMN kappl varchar(2);
ALTER TABLE TABFCSMSEG ALTER COLUMN kappl TYPE varchar(2);
ALTER TABLE TABFCSMSEG ADD COLUMN maktx varchar(40);
ALTER TABLE TABFCSMSEG ALTER COLUMN maktx TYPE varchar(40);
ALTER TABLE TABFCSMSEG ADD COLUMN meins varchar(3);
ALTER TABLE TABFCSMSEG ALTER COLUMN meins TYPE varchar(3);
ALTER TABLE TABFCSMSEG ADD COLUMN mtart varchar(4);
ALTER TABLE TABFCSMSEG ALTER COLUMN mtart TYPE varchar(4);
ALTER TABLE TABFCSMSEG ADD COLUMN uzeit time;
ALTER TABLE TABFCSMSEG ALTER COLUMN uzeit TYPE time;
ALTER TABLE TABFCSMSEG ADD COLUMN xchpf boolean;
ALTER TABLE TABFCSMSEG ALTER COLUMN xchpf TYPE boolean;
