CREATE TABLE IF NOT EXISTS TABFCSLFA1
(
    tenant varchar(10),
    lifnr varchar(10),
    PRIMARY KEY (tenant,lifnr)
);
ALTER TABLE TABFCSLFA1 ADD COLUMN datum date;
ALTER TABLE TABFCSLFA1 ALTER COLUMN datum TYPE date;
ALTER TABLE TABFCSLFA1 ADD COLUMN name1 varchar(80);
ALTER TABLE TABFCSLFA1 ALTER COLUMN name1 TYPE varchar(80);
ALTER TABLE TABFCSLFA1 ADD COLUMN name2 varchar(80);
ALTER TABLE TABFCSLFA1 ALTER COLUMN name2 TYPE varchar(80);
ALTER TABLE TABFCSLFA1 ADD COLUMN stcd1 varchar(16);
ALTER TABLE TABFCSLFA1 ALTER COLUMN stcd1 TYPE varchar(16);
ALTER TABLE TABFCSLFA1 ADD COLUMN stcd2 varchar(11);
ALTER TABLE TABFCSLFA1 ALTER COLUMN stcd2 TYPE varchar(11);
ALTER TABLE TABFCSLFA1 ADD COLUMN stceg varchar(20);
ALTER TABLE TABFCSLFA1 ALTER COLUMN stceg TYPE varchar(20);
ALTER TABLE TABFCSLFA1 ADD COLUMN uname varchar(12);
ALTER TABLE TABFCSLFA1 ALTER COLUMN uname TYPE varchar(12);
ALTER TABLE TABFCSLFA1 ADD COLUMN updfl boolean;
ALTER TABLE TABFCSLFA1 ALTER COLUMN updfl TYPE boolean;
ALTER TABLE TABFCSLFA1 ADD COLUMN uzeit time;
ALTER TABLE TABFCSLFA1 ALTER COLUMN uzeit TYPE time;
