CREATE TABLE IF NOT EXISTS TABFCSMOVSAP
(
    tenant varchar(10),
    movid varchar(50),
    PRIMARY KEY (tenant,movid)
);
ALTER TABLE TABFCSMOVSAP ADD COLUMN aufnr varchar(12);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN aufnr TYPE varchar(12);
ALTER TABLE TABFCSMOVSAP ADD COLUMN bwart varchar(3);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN bwart TYPE varchar(3);
ALTER TABLE TABFCSMOVSAP ADD COLUMN charg varchar(10);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN charg TYPE varchar(10);
ALTER TABLE TABFCSMOVSAP ADD COLUMN charg_to varchar(10);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN charg_to TYPE varchar(10);
ALTER TABLE TABFCSMOVSAP ADD COLUMN datum date;
ALTER TABLE TABFCSMOVSAP ALTER COLUMN datum TYPE date;
ALTER TABLE TABFCSMOVSAP ADD COLUMN kostl varchar(10);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN kostl TYPE varchar(10);
ALTER TABLE TABFCSMOVSAP ADD COLUMN kunnr varchar(10);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN kunnr TYPE varchar(10);
ALTER TABLE TABFCSMOVSAP ADD COLUMN lgort varchar(4);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN lgort TYPE varchar(4);
ALTER TABLE TABFCSMOVSAP ADD COLUMN lgort_to varchar(4);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN lgort_to TYPE varchar(4);
ALTER TABLE TABFCSMOVSAP ADD COLUMN lifnr varchar(10);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN lifnr TYPE varchar(10);
ALTER TABLE TABFCSMOVSAP ADD COLUMN matnr varchar(18);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN matnr TYPE varchar(18);
ALTER TABLE TABFCSMOVSAP ADD COLUMN matnr_to varchar(18);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN matnr_to TYPE varchar(18);
ALTER TABLE TABFCSMOVSAP ADD COLUMN meins varchar(3);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN meins TYPE varchar(3);
ALTER TABLE TABFCSMOVSAP ADD COLUMN menge numeric(13,3);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN menge TYPE numeric(13,3);
ALTER TABLE TABFCSMOVSAP ADD COLUMN menge_to numeric(13,3);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN menge_to TYPE numeric(13,3);
ALTER TABLE TABFCSMOVSAP ADD COLUMN prctr varchar(10);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN prctr TYPE varchar(10);
ALTER TABLE TABFCSMOVSAP ADD COLUMN sobkz varchar(1);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN sobkz TYPE varchar(1);
ALTER TABLE TABFCSMOVSAP ADD COLUMN uname varchar(12);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN uname TYPE varchar(12);
ALTER TABLE TABFCSMOVSAP ADD COLUMN uzeit time;
ALTER TABLE TABFCSMOVSAP ALTER COLUMN uzeit TYPE time;
ALTER TABLE TABFCSMOVSAP ADD COLUMN werks varchar(4);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN werks TYPE varchar(4);
ALTER TABLE TABFCSMOVSAP ADD COLUMN werks_to varchar(4);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN werks_to TYPE varchar(4);
ALTER TABLE TABFCSMOVSAP ADD COLUMN wmsst varchar(1);
ALTER TABLE TABFCSMOVSAP ALTER COLUMN wmsst TYPE varchar(1);
