CREATE TABLE IF NOT EXISTS TABFCSMOVSAPHST
(
    tenant varchar(10),
    movid varchar(50),
    PRIMARY KEY (tenant,movid)
);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN aufnr varchar(12);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN aufnr TYPE varchar(12);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN bwart varchar(3);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN bwart TYPE varchar(3);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN charg varchar(10);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN charg TYPE varchar(10);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN charg_to varchar(10);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN charg_to TYPE varchar(10);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN datum date;
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN datum TYPE date;
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN kostl varchar(10);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN kostl TYPE varchar(10);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN kunnr varchar(10);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN kunnr TYPE varchar(10);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN lgort varchar(4);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN lgort TYPE varchar(4);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN lgort_to varchar(4);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN lgort_to TYPE varchar(4);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN lifnr varchar(10);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN lifnr TYPE varchar(10);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN matnr varchar(18);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN matnr TYPE varchar(18);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN matnr_to varchar(18);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN matnr_to TYPE varchar(18);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN mblnr varchar(10);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN mblnr TYPE varchar(10);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN meins varchar(3);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN meins TYPE varchar(3);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN menge numeric(13,3);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN menge TYPE numeric(13,3);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN menge_to numeric(13,3);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN menge_to TYPE numeric(13,3);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN mjahr varchar(4);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN mjahr TYPE varchar(4);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN prctr varchar(10);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN prctr TYPE varchar(10);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN sobkz varchar(1);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN sobkz TYPE varchar(1);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN uname varchar(12);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN uname TYPE varchar(12);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN uzeit time;
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN uzeit TYPE time;
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN werks varchar(4);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN werks TYPE varchar(4);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN werks_to varchar(4);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN werks_to TYPE varchar(4);
ALTER TABLE TABFCSMOVSAPHST ADD COLUMN wmsst varchar(1);
ALTER TABLE TABFCSMOVSAPHST ALTER COLUMN wmsst TYPE varchar(1);
