# ============================================================
# conditionsSD - configurazione S/4HC
# Communication Arrangement: SAP_COM_0294 + SAP_COM_0008
# ============================================================
s4hc.baseUrl=https://my438840-api.s4hana.cloud.sap
s4hc.username=JAVA_APP_USER
s4hc.password=JavaAppUser_23051995
s4hc.language=IT
